Windlogger: Output Class Reference
Output Class Reference
#include <st_Output.h>
Public Member Functions
Output ()
take care about string length! if data are bigger than strng length ->> soft reset.
virtual ~Output ()
virtual void execute ()
virtual void print ()
bool isEqual (char *name) const
void usart0_print ()
void usart1_print ()
void SDCard_print ()
Public Member Functions inherited from State
State ()
virtual ~State ()
bool isEqual (char *name) const
Static Public Attributes
static const unsigned char USART0 = 1
static const unsigned char USART1 = 2
enable constant for USART0
static const unsigned char SD_CARD = 4
enable constant for USART1
static const unsigned char WIFI = 8
enable constant for SD_CARD
static const unsigned char GPRS = 16
enable constant for WIFI
Private Attributes
char string [100]
Additional Inherited Members
Protected Attributes inherited from State
char m_name [10]
Detailed Description
Definition at line 37 of file st_Output.h.
Constructor & Destructor Documentation
Output()
Output::Output ()
Definition at line 44 of file st_Output.cpp.
References FSM::logger, State::m_name, Logger::output_enable, and USART0.
~Output()
Output::~Output () virtual
Definition at line 49 of file st_Output.cpp.
Member Function Documentation
execute()
void Output::execute () virtual
Implements State.
Definition at line 53 of file st_Output.cpp.
References GPRS, FSM::logger, SD_CARD, SDCard_print(), USART0, usart0_print(), USART1, usart1_print(), and WIFI.
isEqual()
bool Output::isEqual (char * name) const
Definition at line 78 of file st_Output.cpp.
References State::isEqual().
print()
void Output::print () virtual
Implements State.
Definition at line 74 of file st_Output.cpp.
References State::m_name, Usart::print(), and FSM::uart0.
SDCard_print()
void Output::SDCard_print ()
Definition at line 106 of file st_Output.cpp.
Referenced by execute().
usart0_print()
void Output::usart0_print ()
Definition at line 83 of file st_Output.cpp.
References FSM::anemo1, FSM::anemo2, FSM::powerAC, Usart::print(), Sensor::print_average(), FSM::timestamp, FSM::uart0, and FSM::windvane.
Referenced by execute().
usart1_print()
void Output::usart1_print ()
Definition at line 102 of file st_Output.cpp.
Referenced by execute().
Member Data Documentation
GPRS
const unsigned char Output::GPRS = 16 static
Definition at line 68 of file st_Output.h.
Referenced by execute().
SD_CARD
const unsigned char Output::SD_CARD = 4 static
Definition at line 64 of file st_Output.h.
Referenced by execute().
string
char Output::string[100] private
Definition at line 39 of file st_Output.h.
USART0
const unsigned char Output::USART0 = 1 static
Definition at line 60 of file st_Output.h.
Referenced by execute(), and Output().
USART1
const unsigned char Output::USART1 = 2 static
Definition at line 62 of file st_Output.h.
Referenced by execute().
WIFI
const unsigned char Output::WIFI = 8 static
Definition at line 66 of file st_Output.h.
Referenced by execute().
The documentation for this class was generated from the following files:
st_Output.h
st_Output.cpp