Windlogger: Measure Class Reference
Measure Class Reference
The class Measure inherits from the class State.
#include <st_Measure.h>
Public Member Functions
Measure ()
Constructor.
virtual ~Measure ()
Destructor.
virtual void execute ()
The execute method is the measure "main function" The execute function work as this scheme :
virtual void print ()
bool isEqual (char *name) const
Public Member Functions inherited from State
State ()
virtual ~State ()
bool isEqual (char *name) const
Private Member Functions
void clear_data_array ()
this method clear data value to save news
void freq_init_measurement ()
this method initialize frequency measurement for anemometer and RPM
void windvane_value ()
read the windvane value en map it between 0 to 359 degres
void power_read_value ()
read power value - not define realy (see emonLib)
void temperature_read_value ()
read the temperature value from one DS18b20 sensor
void freq_read_value ()
read value from anemometer and RPM
void calc_average ()
calcul average from the data array
Additional Inherited Members
Protected Attributes inherited from State
char m_name [10]
Detailed Description
The timing measure is organize like :
Definition at line 44 of file st_Measure.h.
Constructor & Destructor Documentation
Measure()
Measure::Measure ()
Definition at line 47 of file st_Measure.cpp.
References State::m_name.
~Measure()
Measure::~Measure () virtual
Definition at line 51 of file st_Measure.cpp.
Member Function Documentation
calc_average()
void Measure::calc_average () private
Definition at line 135 of file st_Measure.cpp.
References FSM::anemo1, FSM::anemo2, Power::calc_all(), Sensor::calc_average(), FSM::logger, Logger::measure_counter, FSM::powerAC, and FSM::windvane.
Referenced by execute().
clear_data_array()
void Measure::clear_data_array () private
Definition at line 102 of file st_Measure.cpp.
Referenced by execute().
execute()
void Measure::execute () virtual
Implements State.
Definition at line 57 of file st_Measure.cpp.
References calc_average(), clear_data_array(), FSM::flag_data_averages_ready, FSM::flag_data_frequencies_ready, FSM::flag_new_measure, freq_init_measurement(), freq_read_value(), LED_PIN, FSM::logger, Logger::measure_counter, power_read_value(), temperature_read_value(), and windvane_value().
freq_init_measurement()
void Measure::freq_init_measurement () private
Definition at line 107 of file st_Measure.cpp.
References FSM::anemo1, FSM::anemo2, and Anemometer::start().
Referenced by execute().
freq_read_value()
void Measure::freq_read_value () private
Definition at line 129 of file st_Measure.cpp.
References FSM::anemo1, FSM::anemo2, FSM::logger, and Anemometer::read_value().
Referenced by execute().
isEqual()
bool Measure::isEqual (char * name) const
Definition at line 94 of file st_Measure.cpp.
References State::isEqual().
power_read_value()
void Measure::power_read_value () private
Definition at line 118 of file st_Measure.cpp.
References FSM::logger, FSM::powerAC, and Power::read_rms_value().
Referenced by execute().
print()
void Measure::print () virtual
It's just a simple method to display the state name, use to debug
Implements State.
Definition at line 90 of file st_Measure.cpp.
References State::m_name, Usart::print(), and FSM::uart0.
temperature_read_value()
void Measure::temperature_read_value () private
Definition at line 124 of file st_Measure.cpp.
Referenced by execute().
windvane_value()
void Measure::windvane_value () private
Definition at line 113 of file st_Measure.cpp.
References FSM::logger, Windvane::read_value(), and FSM::windvane.
Referenced by execute().
The documentation for this class was generated from the following files:
st_Measure.h
st_Measure.cpp