Windlogger: RTC Class Reference
RTC Class Reference
The RTC class regroup methods and parameters to use the Real Time Clock : pcf8563 This class use the TWI class to drive the atmega1284p's TWI peripheral.
#include <RTC.h>
Public Member Functions
RTC ()
virtual ~RTC ()
unsigned char get_second () const
unsigned long get_timestamp ()
unsigned char get_date ()
void update_reg (unsigned char reg, unsigned char data)
Function to update a register in the pcf8563 This function is use in the st_config class.
void print_config ()
Public Attributes
const unsigned char SECS = 0x02
const unsigned char MINS = 0x03
const unsigned char HOURS = 0x04
const unsigned char DAY = 0x05
const unsigned char WEEKDAY = 0x06
const unsigned char MONTH = 0x07
const unsigned char YEAR = 0x08
Private Member Functions
unsigned long time_to_epoch (Time &start, Time &stop)
unsigned char is_leap_year (unsigned int year)
char a2toBCD (char &s_nombre)
unsigned char utoBCD (unsigned char _data)
Private Attributes
char JOURS [8][3] ={"Su","Mo","Tu","We","Th","Fr","Sa","er"}
Time epoch_010116
Time m_time
const unsigned long EPOCH_TIMESTAMP = 1420156800
Detailed Description
Definition at line 53 of file RTC.h.
Constructor & Destructor Documentation
RTC()
RTC::RTC ()
Class constructor
Definition at line 38 of file RTC.cpp.
References Time::day, epoch_010116, Time::hours, Time::mins, Time::month, Time::secs, and Time::year.
~RTC()
RTC::~RTC () virtual
class destructor
Definition at line 49 of file RTC.cpp.
Member Function Documentation
a2toBCD()
char RTC::a2toBCD (char & s_nombre) private
This function convert two char number in BCD format because pcf8563 register are in BCD format
Parameters
s_nombre that is a reference to a string char
Returns
décalage de 4 bits des dizaine pour coder le nombre en BCD sur 2 quartets (1 octet)
Definition at line 240 of file RTC.cpp.
get_date()
uint8_t RTC::get_date ()
Function to get time and date registers from the pcf8563 and store them in the local m_time structure.
Returns
return 0 if it's ok or if have TWI error.
Definition at line 171 of file RTC.cpp.
References Time::day, Time::hours, JOURS, m_time, Time::mins, Time::month, TWI::receive(), Time::secs, FSM::twi, Time::weekday, and Time::year.
Referenced by main().
get_second()
unsigned char RTC::get_second () const inline
Definition at line 82 of file RTC.h.
Referenced by main(), and FSM::measurement_timing_control().
get_timestamp()
unsigned long RTC::get_timestamp ()
Definition at line 280 of file RTC.cpp.
References epoch_010116, EPOCH_TIMESTAMP, m_time, and time_to_epoch().
Referenced by Output::execute().
is_leap_year()
unsigned char RTC::is_leap_year (unsigned int year) private
is_leap_year function return 0 if year is not a leap year and 1 when it is.
Parameters
year year want to by tested
Returns
return 0 if year is not a leap year and 1 when it is.
function to return if the ear is leap
Parameters
year the year to test
Returns
0 for false, 1 for true
Definition at line 112 of file RTC.cpp.
Referenced by time_to_epoch().
print_config()
void RTC::print_config ()
This function print on the uartO the RTC's config information
Definition at line 267 of file RTC.cpp.
References Time::day, Time::hours, m_time, Time::mins, Time::month, Usart::print(), Time::secs, FSM::uart0, Time::weekday, and Time::year.
Referenced by Config::display().
time_to_epoch()
unsigned long RTC::time_to_epoch (Time & start, Time & stop) private
The time to epoch method convert m_time registers in the timestamp format.
Parameters
start That is actually a structure egal to 01/01/16 at 00:00:00
stop that is actually the m_time member
Definition at line 125 of file RTC.cpp.
References Time::day, Time::hours, is_leap_year(), Time::mins, Time::month, Time::secs, and Time::year.
Referenced by get_timestamp().
update_reg()
void RTC::update_reg (unsigned char reg, unsigned char data)
Parameters
reg register adress
data byte data
Definition at line 261 of file RTC.cpp.
References TWI::set_char(), FSM::twi, and utoBCD().
Referenced by Config::execute().
utoBCD()
uint8_t RTC::utoBCD (unsigned char _data) private
This function convert an unsigned char number in unsigned char BCD format because pcf8563 register are in BCD format
Parameters
_data that is a the number need to be converted
Definition at line 255 of file RTC.cpp.
Referenced by update_reg().
Member Data Documentation
DAY
const unsigned char RTC::DAY = 0x05
pcf8563 day register adress
Definition at line 74 of file RTC.h.
epoch_010116
Time RTC::epoch_010116 private
Used for time_to_epoch calc
Definition at line 117 of file RTC.h.
Referenced by get_timestamp(), and RTC().
EPOCH_TIMESTAMP
const unsigned long RTC::EPOCH_TIMESTAMP = 1420156800 private
Definition at line 121 of file RTC.h.
Referenced by get_timestamp().
HOURS
const unsigned char RTC::HOURS = 0x04
pcf8563 hours register adress
Definition at line 73 of file RTC.h.
JOURS
char RTC::JOURS[8][3] ={"Su","Mo","Tu","We","Th","Fr","Sa","er"} private
this array permit to convert weekday number in a small string
Definition at line 115 of file RTC.h.
Referenced by get_date().
m_time
Time RTC::m_time private
m_time is the structure where is store current time and date
Definition at line 119 of file RTC.h.
Referenced by get_date(), get_timestamp(), and print_config().
MINS
const unsigned char RTC::MINS = 0x03
pcf8563 minutes register adress
Definition at line 72 of file RTC.h.
MONTH
const unsigned char RTC::MONTH = 0x07
pcf8563 month register adress
Definition at line 76 of file RTC.h.
SECS
const unsigned char RTC::SECS = 0x02
pcf8563 seconds register adress
Definition at line 71 of file RTC.h.
WEEKDAY
const unsigned char RTC::WEEKDAY = 0x06
pcf8563 weekday register adress
Definition at line 75 of file RTC.h.
YEAR
const unsigned char RTC::YEAR = 0x08
pcf8563 year register adress
Definition at line 77 of file RTC.h.
The documentation for this class was generated from the following files:
RTC.h
RTC.cpp