Windlogger: TWI Class Reference
TWI Class Reference
#include <TWI.h>
Public Member Functions
TWI ()
virtual ~TWI ()
unsigned char print (unsigned char, unsigned char, unsigned char, unsigned char *)
unsigned char receive (unsigned char, unsigned char, unsigned char, unsigned char *)
unsigned char set_char (unsigned char addr, unsigned char reg, unsigned char data)
unsigned char get_char (unsigned char addr, unsigned char reg)
Private Member Functions
void start ()
void restart ()
void stop ()
void set (unsigned char data)
unsigned char get_ack (void)
unsigned char get_nack (void)
unsigned char get_status (void)
Detailed Description
Definition at line 34 of file TWI.h.
Constructor & Destructor Documentation
TWI()
TWI::TWI ()
Definition at line 37 of file TWI.cpp.
~TWI()
TWI::~TWI () virtual
Definition at line 43 of file TWI.cpp.
Member Function Documentation
get_ack()
uint8_t TWI::get_ack (void) private
Definition at line 89 of file TWI.cpp.
Referenced by receive().
get_char()
uint8_t TWI::get_char (unsigned char addr, unsigned char reg)
Definition at line 141 of file TWI.cpp.
References get_nack(), get_status(), restart(), start(), and stop().
get_nack()
uint8_t TWI::get_nack (void) private
Definition at line 99 of file TWI.cpp.
Referenced by get_char(), and receive().
get_status()
uint8_t TWI::get_status (void) private
Definition at line 110 of file TWI.cpp.
Referenced by get_char(), print(), receive(), and set_char().
print()
uint8_t TWI::print (unsigned char, unsigned char, unsigned char, unsigned char *)
Definition at line 176 of file TWI.cpp.
References get_status(), start(), and stop().
receive()
uint8_t TWI::receive (unsigned char, unsigned char, unsigned char, unsigned char *)
Definition at line 203 of file TWI.cpp.
References get_ack(), get_nack(), get_status(), restart(), start(), and stop().
Referenced by RTC::get_date().
restart()
void TWI::restart () private
Definition at line 61 of file TWI.cpp.
Referenced by get_char(), and receive().
set()
void TWI::set (unsigned char data) private
Definition at line 79 of file TWI.cpp.
set_char()
uint8_t TWI::set_char (unsigned char addr, unsigned char reg, unsigned char data)
Definition at line 117 of file TWI.cpp.
References get_status(), start(), and stop().
Referenced by RTC::update_reg().
start()
void TWI::start () private
Definition at line 50 of file TWI.cpp.
Referenced by get_char(), print(), receive(), and set_char().
stop()
void TWI::stop () private
Definition at line 71 of file TWI.cpp.
Referenced by get_char(), print(), receive(), and set_char().
The documentation for this class was generated from the following files:
TWI.h
TWI.cpp