Windlogger: State Class Reference
State Class Reference abstract
#include <State.h>
Public Member Functions
State ()
virtual ~State ()
virtual void execute ()=0
virtual void print ()=0
bool isEqual (char *name) const
Protected Attributes
char m_name [10]
Detailed Description
Definition at line 34 of file State.h.
Constructor & Destructor Documentation
State()
State::State ()
Definition at line 42 of file State.cpp.
~State()
State::~State () virtual
Definition at line 46 of file State.cpp.
Member Function Documentation
execute()
virtual void State::execute () pure virtual
Implemented in Config, Measure, Idle, Output, and Sleep.
Referenced by FSM::execute().
isEqual()
bool State::isEqual (char * name) const
Definition at line 50 of file State.cpp.
References m_name.
Referenced by Sleep::isEqual(), Output::isEqual(), Idle::isEqual(), Measure::isEqual(), and Config::isEqual().
print()
virtual void State::print () pure virtual
Implemented in Config, Measure, Idle, Output, and Sleep.
Member Data Documentation
m_name
char State::m_name[10] protected
state name initialize with the constructor
Definition at line 36 of file State.h.
Referenced by Config::Config(), Idle::Idle(), isEqual(), Measure::Measure(), Output::Output(), Output::print(), Idle::print(), Measure::print(), and Config::print().
The documentation for this class was generated from the following files:
State.h
State.cpp