Windlogger: Usart Class Reference
Usart Class Reference
This is the uart library for the atmega1284p.
#include <Usart.h>
Public Member Functions
Usart (unsigned char usart, unsigned int baudrate)
Usart constructor on asynchronous mode.
void set (char character)
USART char sender function.
void print (char *string)
USART string sender function.
Static Public Attributes
static bool flag_rx0 = 0
static bool flag_rx1
static char data_udr0 = 0
static char data_udr1
static const unsigned int BR_9600 = 207
static const unsigned int BR_57600 = 34
static const unsigned int BR_115200 = 16
Private Attributes
unsigned char m_usart
Detailed Description
This class permit to define, the uart0 and uart1. It's possible to send data as char or string. Interruption needs to be set for receive char.
Definition at line 41 of file Usart.h.
Constructor & Destructor Documentation
Usart()
Usart::Usart (unsigned char usart, unsigned int baudrate)
Parameters
usart 0 for usart0 or 1 for usart1
baudrate Use BR_XXXX constant to define baude rate speed
Definition at line 46 of file Usart.cpp.
References m_usart.
Member Function Documentation
print()
void Usart::print (char * string)
Parameters
string The string to send on the USART0
Definition at line 99 of file Usart.cpp.
Referenced by FSM::character_processing(), Config::display(), Config::execute(), main(), Sleep::print(), Output::print(), Idle::print(), Measure::print(), Config::print(), Sensor::print_config(), RTC::print_config(), Power::print_config(), Sensor::print_data_array(), Power::print_data_array(), Power::readVcc(), and Output::usart0_print().
set()
void Usart::set (char character)
Parameters
character The character to send on the USART0
Definition at line 84 of file Usart.cpp.
References m_usart.
Referenced by FSM::character_processing(), Sensor::print_data_array(), and Power::print_data_array().
Member Data Documentation
BR_115200
const unsigned int Usart::BR_115200 = 16 static
UBBRn registers value to work at 115200 baud
Definition at line 63 of file Usart.h.
BR_57600
const unsigned int Usart::BR_57600 = 34 static
UBBRn registers value to work at 57600 baud
Definition at line 62 of file Usart.h.
BR_9600
const unsigned int Usart::BR_9600 = 207 static
UBBRn registers value to work at 9600 baud
Definition at line 61 of file Usart.h.
data_udr0
char Usart::data_udr0 = 0 static
This register permit at the usart0 rx interrupt to store the UDR register>
Definition at line 55 of file Usart.h.
Referenced by FSM::character_processing(), and ISR().
data_udr1
char Usart::data_udr1 static
This register permit at the usart1 rx interrupt to store the UDR register>
Definition at line 56 of file Usart.h.
flag_rx0
bool Usart::flag_rx0 = 0 static
Is set by the uart0 rx interrupt>
Definition at line 49 of file Usart.h.
Referenced by FSM::character_processing(), ISR(), and main().
flag_rx1
bool Usart::flag_rx1 static
Is set by the uart1 rx interrupt>
Definition at line 50 of file Usart.h.
m_usart
unsigned char Usart::m_usart private
this is the uart number memory
Definition at line 43 of file Usart.h.
Referenced by set(), and Usart().
The documentation for this class was generated from the following files:
Usart.h
Usart.cpp