Windlogger: Anemometer Class Reference
Anemometer Class Reference
#include <Anemometer.h>
Public Member Functions
Anemometer (unsigned char id)
virtual ~Anemometer ()
char * print (char *string)
void read_value (unsigned char measure_number)
Public Member Functions inherited from Sensor
Sensor (unsigned char id)
virtual ~Sensor ()
void set_factor (double factor)
void set_offset (double offset)
void set_enable (double enable)
unsigned char is_enable () const
void read_value (unsigned char measure_number)
void print_config (char arg_id0[], char arg_id1[], char arg_id2[])
This method print the sensor configuration for the sensor. It's a good idea to overload this function to do it more explicit for each sensor.
void calc_average ()
This method calculate the average from the data array.
char * print_average (unsigned char prec, char *string)
The print_average method print the average's value in the string.
void print_data_array () const
void load_param ()
Load saved parameters for sensors from the eeprom.
void update_param ()
Update saved parameters for sensors in the eeprom.
void initialize_param ()
Initialize the eeprom memory.
Static Public Member Functions
static void start ()
Public Attributes
const double TIMER3_OVF_PERIODE = (double) 65536/15625.0
Additional Inherited Members
Protected Member Functions inherited from Sensor
int adc_value (unsigned char channel)
This method read return int value from the ADC channel.
Protected Attributes inherited from Sensor
unsigned char m_id
unsigned char m_enable
unsigned char m_eeprom_addr
double m_data [MAX_DATA_SAMPLE] ={0.0}
double m_average
double m_factor
double m_offset
Detailed Description
Definition at line 36 of file Anemometer.h.
Constructor & Destructor Documentation
Anemometer()
Anemometer::Anemometer (unsigned char id)
Definition at line 39 of file Anemometer.cpp.
References Sensor::m_id.
~Anemometer()
Anemometer::~Anemometer () virtual
Definition at line 63 of file Anemometer.cpp.
Member Function Documentation
print()
char * Anemometer::print (char * string) virtual
This method need to be overload to personalize sensor config display's
Returns
return string pointer
Reimplemented from Sensor.
Definition at line 67 of file Anemometer.cpp.
References Sensor::m_id.
read_value()
void Anemometer::read_value (unsigned char measure_number)
This method read the sensors value, needs to be implemented for each sensor
Definition at line 74 of file Anemometer.cpp.
References Sensor::is_enable(), Sensor::m_data, Sensor::m_factor, Sensor::m_id, Sensor::m_offset, and TIMER3_OVF_PERIODE.
Referenced by Measure::freq_read_value().
start()
void Anemometer::start () static
Definition at line 99 of file Anemometer.cpp.
Referenced by Measure::freq_init_measurement().
Member Data Documentation
TIMER3_OVF_PERIODE
const double Anemometer::TIMER3_OVF_PERIODE = (double) 65536/15625.0
Definition at line 54 of file Anemometer.h.
Referenced by read_value().
The documentation for this class was generated from the following files:
Anemometer.h
Anemometer.cpp