Windlogger: Sensor Class Reference
Sensor Class Reference
The sensor class is the base container for sensor, need to create a inherited class from sensor.
#include <Sensor.h>
Public Member Functions
Sensor (unsigned char id)
virtual ~Sensor ()
void set_factor (double factor)
void set_offset (double offset)
void set_enable (double enable)
unsigned char is_enable () const
virtual char * print (char *string)
void read_value (unsigned char measure_number)
void print_config (char arg_id0[], char arg_id1[], char arg_id2[])
This method print the sensor configuration for the sensor. It's a good idea to overload this function to do it more explicit for each sensor.
void calc_average ()
This method calculate the average from the data array.
char * print_average (unsigned char prec, char *string)
The print_average method print the average's value in the string.
void print_data_array () const
void load_param ()
Load saved parameters for sensors from the eeprom.
void update_param ()
Update saved parameters for sensors in the eeprom.
void initialize_param ()
Initialize the eeprom memory.
Protected Member Functions
int adc_value (unsigned char channel)
This method read return int value from the ADC channel.
Protected Attributes
unsigned char m_id
unsigned char m_enable
unsigned char m_eeprom_addr
double m_data [MAX_DATA_SAMPLE] ={0.0}
double m_average
double m_factor
double m_offset
Detailed Description
The sensor class give a sensor skeleton, this allow you to create an inherited sensor class. Take a look on sen_** class for more details.
Definition at line 43 of file Sensor.h.
Constructor & Destructor Documentation
Sensor()
Sensor::Sensor (unsigned char id)
Class constructor
< This calc permit to store sensor data each 16 bytes after the EEPROM_OFFSET
Definition at line 46 of file Sensor.cpp.
References EEPROM_OFFSET, load_param(), m_eeprom_addr, and m_id.
~Sensor()
Sensor::~Sensor () virtual
class destructor
Definition at line 50 of file Sensor.cpp.
Member Function Documentation
adc_value()
int Sensor::adc_value (unsigned char channel) protected
this is the sensor's offset. It initial value is zero. Change it if you want add an offset to the sensor's data.
Parameters
channel (0 to 7) from ADC pin mapping
Returns
int value of the ADC conversion
This method permit to do conversion from adc channel
Parameters
channel
Returns
Use the AVcc for voltage reference and add the channel number
ADEN : conversion enable, ADPS[2:0] : divide the ADC frequency clock, ADSC : start one conversion
wait for conversion to complete
Stop the ADC (reduce power)
Definition at line 139 of file Sensor.cpp.
Referenced by Windvane::read_value().
calc_average()
void Sensor::calc_average ()
Definition at line 76 of file Sensor.cpp.
References is_enable(), FSM::logger, m_average, m_data, and Logger::measure_max.
Referenced by Measure::calc_average(), and is_enable().
initialize_param()
void Sensor::initialize_param ()
Returns
void
Definition at line 127 of file Sensor.cpp.
Referenced by is_enable().
is_enable()
unsigned char Sensor::is_enable () const inline
Definition at line 71 of file Sensor.h.
References calc_average(), initialize_param(), load_param(), m_enable, print(), print_average(), print_config(), print_data_array(), read_value(), and update_param().
Referenced by calc_average(), print_average(), and Anemometer::read_value().
load_param()
void Sensor::load_param ()
Returns
void
Definition at line 113 of file Sensor.cpp.
References m_eeprom_addr, m_enable, m_factor, and m_offset.
Referenced by FSM::FSM(), is_enable(), and Sensor().
print()
char * Sensor::print (char * string) virtual
This method need to be overload to personalize config display for the sensor
Returns
return string pointer
Reimplemented in Anemometer, and Windvane.
Definition at line 58 of file Sensor.cpp.
References m_id.
Referenced by is_enable(), and print_config().
print_average()
char * Sensor::print_average (unsigned char prec, char * string)
Definition at line 89 of file Sensor.cpp.
References is_enable(), and m_average.
Referenced by is_enable(), and Output::usart0_print().
print_config()
void Sensor::print_config (char arg_id0[], char arg_id1[], char arg_id2[])
Definition at line 66 of file Sensor.cpp.
References m_enable, m_factor, m_offset, print(), Usart::print(), and FSM::uart0.
Referenced by Config::display(), and is_enable().
print_data_array()
void Sensor::print_data_array () const
Definition at line 100 of file Sensor.cpp.
References m_data, Usart::print(), Usart::set(), and FSM::uart0.
Referenced by is_enable().
read_value()
void Sensor::read_value (unsigned char measure_number)
This method read the sensors value, needs to be implemented for each sensor
Referenced by is_enable().
set_enable()
void Sensor::set_enable (double enable) inline
Definition at line 66 of file Sensor.h.
References m_enable, and update_param().
Referenced by Config::execute().
set_factor()
void Sensor::set_factor (double factor) inline
Definition at line 62 of file Sensor.h.
References m_factor, and update_param().
Referenced by Config::execute().
set_offset()
void Sensor::set_offset (double offset) inline
Definition at line 64 of file Sensor.h.
References m_offset, and update_param().
Referenced by Config::execute().
update_param()
void Sensor::update_param ()
Returns
void
Definition at line 120 of file Sensor.cpp.
References m_eeprom_addr, m_enable, m_factor, and m_offset.
Referenced by is_enable(), set_enable(), set_factor(), and set_offset().
Member Data Documentation
m_average
double Sensor::m_average protected
there is the result from the m_data average
Definition at line 135 of file Sensor.h.
Referenced by calc_average(), and print_average().
m_data
double Sensor::m_data[MAX_DATA_SAMPLE] ={0.0} protected
this is the data array where witch data are put and from where the average is done.
Definition at line 133 of file Sensor.h.
Referenced by calc_average(), print_data_array(), Windvane::read_value(), and Anemometer::read_value().
m_eeprom_addr
unsigned char Sensor::m_eeprom_addr protected
This is the eeprom address calc from the m_id and the EEPROM_OFFSET
Definition at line 131 of file Sensor.h.
Referenced by load_param(), Sensor(), and update_param().
m_enable
unsigned char Sensor::m_enable protected
If enable is off, the sensor is not process
Definition at line 129 of file Sensor.h.
Referenced by is_enable(), load_param(), print_config(), set_enable(), and update_param().
m_factor
double Sensor::m_factor protected
Definition at line 137 of file Sensor.h.
Referenced by load_param(), print_config(), Anemometer::read_value(), Windvane::read_value(), set_factor(), and update_param().
m_id
unsigned char Sensor::m_id protected
this the sensor's id in the Eeprom::sensor_counter
Definition at line 127 of file Sensor.h.
Referenced by Anemometer::Anemometer(), Anemometer::print(), print(), Anemometer::read_value(), and Sensor().
m_offset
double Sensor::m_offset protected
this is the sensor's factor. it initial value is 1, but if the sensor data need to be multiply, change the factor value.
Definition at line 139 of file Sensor.h.
Referenced by load_param(), print_config(), Anemometer::read_value(), Windvane::read_value(), set_offset(), and update_param().
The documentation for this class was generated from the following files:
Sensor.h
Sensor.cpp