Windlogger: powerDC Class Reference
powerDC Class Reference
#include <powerDC.h>
Public Member Functions
powerDC (unsigned char v_pin, unsigned char i_pin, unsigned char id)
virtual ~powerDC ()
char * Power::print (char *string)
void Power::read_values (unsigned char measure_number, unsigned int timeout)
void Power::calc_averages ()
void Power::print_config (char arg_id1[], char arg_id2[], char arg_id3[], char arg_id4[], char arg_id5[], char arg_id6[])
char * Power::print_average (unsigned char prec, char *string)
void Power::print_data_array ()
Public Member Functions inherited from Power
Power (unsigned char v_pin, unsigned char i_pin, unsigned char id)
virtual ~Power ()
void set_v_factor (double factor)
void set_v_offset (double offset)
void set_v_phase (double phase)
void set_i_factor (double factor)
void set_i_offset (double offset)
virtual char * print (char *string)
void read_rms_value (unsigned char measure_number, unsigned int crossings, unsigned int timeout)
void read_dc_value (unsigned char measure_number, unsigned int timeout)
void print_config (char arg_id1[], char arg_id2[], char arg_id3[], char arg_id4[], char arg_id5[], char arg_id6[])
This method print the configuration for the power measurement. It's a good idea to overload this function to do it more explicit for each sensor.
void calc_all ()
This method calculate the mean RMS voltage, mean RMS current, active power, apparent power and power factor from the data array.
char * print_average (unsigned char prec, char *string)
The print_average method print the average's value in the string.
void print_data_array () const
void load_param ()
Load saved parameters for sensors from the eeprom.
void update_param ()
Update saved parameters for sensors in the eeprom.
void initialize_param ()
Initialize the eeprom memory.
long readVcc ()
Reads the VCC used during the ADC conversion.
Additional Inherited Members
Protected Member Functions inherited from Power
int adc_value (unsigned char channel)
This method read return int value from the ADC channel.
Protected Attributes inherited from Power
const int ADC_COUNTS = 1024
unsigned char m_v_pin
unsigned char m_i_pin
double p_data [MAX_DATA_SAMPLE] ={0.0}
double s_data [MAX_DATA_SAMPLE] ={0.0}
double pf_data [MAX_DATA_SAMPLE] ={0.0}
double p_average
double s_average
double pf_average
double v_data [MAX_DATA_SAMPLE] ={0.0}
double v_average
double v_factor
double v_offset
double v_phase
double i_data [MAX_DATA_SAMPLE] ={0.0}
double i_average
double i_factor
double i_offset
double Vmeas
double Imeas
double Vshifted
long double sumP
long double sumV
long double sumI
double referenceV
double v_filtered
double i_filtered
long showSupply
int startV
bool lastVCross
bool checkVCross
unsigned char m_id
unsigned char m_eeprom_addr
Detailed Description
Definition at line 36 of file powerDC.h.
Constructor & Destructor Documentation
powerDC()
powerDC::powerDC (unsigned char v_pin, unsigned char i_pin, unsigned char id)
< This calc permit to store sensor data each 16 bytes after the EEPROM_OFFSET
Definition at line 37 of file powerDC.cpp.
References EEPROM_OFFSET, Power::load_param(), Power::m_eeprom_addr, Power::m_id, Power::v_offset, and Power::Vmeas.
~powerDC()
powerDC::~powerDC () virtual
Definition at line 46 of file powerDC.cpp.
References Power::ADC_COUNTS, Power::adc_value(), Power::i_average, Power::i_data, Power::i_factor, Power::i_filtered, Power::i_offset, Power::Imeas, FSM::logger, Power::m_id, Logger::measure_max, Power::p_average, Power::p_data, Power::calc_averages(), Power::read_values(), Usart::print(), Power::print(), Power::print_average(), Power::print_config(), Power::print_data_array(), Usart::set(), Power::showSupply, Power::sumI, Power::sumP, Power::sumV, FSM::uart0, Power::v_average, Power::v_data, Power::v_factor, Power::v_offset, and Power::Vmeas.
Member Function Documentation
Power::calc_averages()
void powerDC::Power::calc_averages ()
Referenced by ~powerDC().
Power::print()
char* powerDC::Power::print (char * string)
Power::print_average()
char* powerDC::Power::print_average (unsigned char prec, char * string)
Power::print_config()
void powerDC::Power::print_config (char arg_id1[], char arg_id2[], char arg_id3[], char arg_id4[], char arg_id5[], char arg_id6[])
Power::print_data_array()
void powerDC::Power::print_data_array () inline
Definition at line 66 of file powerDC.h.
Power::read_values()
void powerDC::Power::read_values (unsigned char measure_number, unsigned int timeout)
Referenced by ~powerDC().
The documentation for this class was generated from the following files:
powerDC.h
powerDC.cpp