Windlogger: Power Class Reference
Power Class Reference
The Power class is the base container for measuring and calculating power.
#include <Power.h>
Public Member Functions
Power (unsigned char v_pin, unsigned char i_pin, unsigned char id)
virtual ~Power ()
void set_v_factor (double factor)
void set_v_offset (double offset)
void set_v_phase (double phase)
void set_i_factor (double factor)
void set_i_offset (double offset)
virtual char * print (char *string)
void read_rms_value (unsigned char measure_number, unsigned int crossings, unsigned int timeout)
void print_config (char arg_id1[], char arg_id2[], char arg_id3[], char arg_id4[], char arg_id5[], char arg_id6[])
This method print the configuration for the power measurement. It's a good idea to overload this function to do it more explicit for each sensor.
void calc_all ()
This method calculate the mean RMS voltage, mean RMS current, active power, apparent power and power factor from the data array.
char * print_average (unsigned char prec, char *string)
The print_average method print the average's value in the string.
void print_data_array () const
void load_param ()
Load saved parameters for sensors from the eeprom.
void update_param ()
Update saved parameters for sensors in the eeprom.
void initialize_param ()
Initialize the eeprom memory.
long readVcc ()
Reads the VCC used during the ADC conversion.
Protected Member Functions
int adc_value (unsigned char channel)
This method read return int value from the ADC channel.
Protected Attributes
const int ADC_COUNTS = 1024
unsigned char m_v_pin
unsigned char m_i_pin
double p_data [MAX_DATA_SAMPLE] ={0.0}
double s_data [MAX_DATA_SAMPLE] ={0.0}
double pf_data [MAX_DATA_SAMPLE] ={0.0}
double p_average
double s_average
double pf_average
double v_data [MAX_DATA_SAMPLE] ={0.0}
double v_average
double v_factor
double v_offset
double v_phase
double i_data [MAX_DATA_SAMPLE] ={0.0}
double i_average
double i_factor
double i_offset
double Vmeas
double Imeas
double Vshifted
long double sumP
long double sumV
long double sumI
double referenceV
double v_filtered
double i_filtered
long showSupply
int startV
bool lastVCross
bool checkVCross
unsigned char m_id
unsigned char m_eeprom_addr
Detailed Description
The Power class gives base layer for any type of power calculation, either AC or DC. Take a look on pow_** class for more details.
Definition at line 65 of file Power.h.
Constructor & Destructor Documentation
Power()
Power::Power (unsigned char v_pin, unsigned char i_pin, unsigned char id)
Class constructor
< This calc permit to store sensor data each 16 bytes after the EEPROM_OFFSET
Definition at line 49 of file Power.cpp.
References checkVCross, EEPROM_OFFSET, load_param(), m_eeprom_addr, m_id, v_offset, and Vmeas.
~Power()
Power::~Power () virtual
class destructor
Definition at line 58 of file Power.cpp.
Member Function Documentation
adc_value()
int Power::adc_value (unsigned char channel) protected
Parameters
channel (0 to 7) from ADC pin mapping
Returns
int value of the ADC conversion
This method permit to do conversion from adc channel
Parameters
channel
Returns
Use the AVcc for voltage reference and add the channel number
ADEN : conversion enable, ADPS[2:0] : divide the ADC frequency clock, ADSC : start one conversion
wait for conversion to complete
Stop the ADC (reduce power)
Definition at line 308 of file Power.cpp.
Referenced by read_rms_value().
calc_all()
void Power::calc_all ()
Definition at line 208 of file Power.cpp.
References i_average, i_data, FSM::logger, Logger::measure_max, p_average, p_data, pf_average, pf_data, s_average, s_data, v_average, and v_data.
Referenced by Measure::calc_average(), and set_i_offset().
initialize_param()
void Power::initialize_param ()
Returns
void
Definition at line 296 of file Power.cpp.
Referenced by set_i_offset().
load_param()
void Power::load_param ()
Returns
void
Definition at line 274 of file Power.cpp.
References i_factor, i_offset, m_eeprom_addr, m_i_pin, m_v_pin, v_factor, v_offset, and v_phase.
Referenced by FSM::FSM(), Power(), and set_i_offset().
print()
char * Power::print (char * string) virtual
This method displays the config for the power class
Returns
return string pointer
Definition at line 66 of file Power.cpp.
References m_id.
Referenced by print_config(), and set_i_offset().
print_average()
char * Power::print_average (unsigned char prec, char * string)
Definition at line 237 of file Power.cpp.
References i_average, p_average, pf_average, s_average, and v_average.
Referenced by set_i_offset(), and Output::usart0_print().
print_config()
void Power::print_config (char arg_id1[], char arg_id2[], char arg_id3[], char arg_id4[], char arg_id5[], char arg_id6[])
Definition at line 74 of file Power.cpp.
References i_factor, i_offset, Usart::print(), print(), showSupply, FSM::uart0, v_factor, v_offset, and v_phase.
Referenced by Config::display(), and set_i_offset().
print_data_array()
void Power::print_data_array () const
Definition at line 257 of file Power.cpp.
References i_data, FSM::logger, Logger::measure_max, p_data, pf_data, Usart::print(), s_data, Usart::set(), FSM::uart0, and v_data.
Referenced by set_i_offset().
read_rms_value()
void Power::read_rms_value (unsigned char measure_number, unsigned int crossings, unsigned int timeout)
This method read the sensors value for the power class and calculates the rms values. Needs a reference V to calculate power.
@ todo use m_v_pin and m_i_pin def and correct the bug
Definition at line 89 of file Power.cpp.
References ADC_COUNTS, adc_value(), checkVCross, i_data, i_factor, i_filtered, i_offset, Imeas, lastVCross, m_v_pin, p_data, pf_data, referenceV, s_data, showSupply, startV, sumI, sumP, sumV, v_data, v_factor, v_filtered, v_offset, v_phase, Vmeas, and Vshifted.
Referenced by Measure::power_read_value(), and set_i_offset().
readVcc()
long Power::readVcc ()
This method reads the reference VCC voltage used during the ADC convertiona.
Returns
void
Parameters
none
Returns
VCC
Draft for the moment, not used
Use internal 1.1V voltage reference and read Vcc/2 on the channel 5
ADEN : conversion enable, ADPS[2:0] : divide the ADC frequency clock, ADSC : start one conversion
wait for conversion to complete
Stop the ADC (reduce power)
Definition at line 330 of file Power.cpp.
References Usart::print(), READVCC_CALIBRATION_CONST, and FSM::uart0.
Referenced by set_i_offset().
set_i_factor()
void Power::set_i_factor (double factor) inline
Definition at line 99 of file Power.h.
References i_factor, and update_param().
Referenced by Config::execute().
set_i_offset()
void Power::set_i_offset (double offset) inline
Definition at line 101 of file Power.h.
References calc_all(), i_offset, initialize_param(), load_param(), print(), print_average(), print_config(), print_data_array(), read_rms_value(), readVcc(), and update_param().
Referenced by Config::execute().
set_v_factor()
void Power::set_v_factor (double factor) inline
Definition at line 89 of file Power.h.
References update_param(), and v_factor.
Referenced by Config::execute().
set_v_offset()
void Power::set_v_offset (double offset) inline
Definition at line 91 of file Power.h.
References update_param(), and v_offset.
Referenced by Config::execute().
set_v_phase()
void Power::set_v_phase (double phase) inline
Definition at line 93 of file Power.h.
References update_param(), and v_phase.
Referenced by Config::execute().
update_param()
void Power::update_param ()
Returns
void
Definition at line 285 of file Power.cpp.
References i_factor, i_offset, m_eeprom_addr, m_i_pin, m_v_pin, v_factor, v_offset, and v_phase.
Referenced by set_i_factor(), set_i_offset(), set_v_factor(), set_v_offset(), and set_v_phase().
Member Data Documentation
ADC_COUNTS
const int Power::ADC_COUNTS = 1024 protected
Definition at line 169 of file Power.h.
Referenced by read_rms_value().
checkVCross
bool Power::checkVCross protected
Used to measure number of times threshold is crossed.
Definition at line 228 of file Power.h.
Referenced by Power(), and read_rms_value().
i_average
double Power::i_average protected
there is the result from the m_data average
Definition at line 204 of file Power.h.
Referenced by calc_all(), and print_average().
i_data
double Power::i_data[MAX_DATA_SAMPLE] ={0.0} protected
this is the phase delay of the voltage offset. It initial value is zero. Change it if you want add an offset to the sensor's data. this is the where current data is stored and used to calculate the average.
Definition at line 203 of file Power.h.
Referenced by calc_all(), print_data_array(), and read_rms_value().
i_factor
double Power::i_factor protected
Definition at line 205 of file Power.h.
Referenced by load_param(), print_config(), read_rms_value(), set_i_factor(), and update_param().
i_filtered
double Power::i_filtered protected
Definition at line 218 of file Power.h.
Referenced by read_rms_value().
i_offset
double Power::i_offset protected
this is the current calibartion factor. it initial value is 1, but if the sensor data need to be multiply, change the factor value.
Definition at line 206 of file Power.h.
Referenced by load_param(), print_config(), read_rms_value(), set_i_offset(), and update_param().
Imeas
double Power::Imeas protected
Variable that holds measurement
Definition at line 214 of file Power.h.
Referenced by read_rms_value().
lastVCross
bool Power::lastVCross protected
Definition at line 228 of file Power.h.
Referenced by read_rms_value().
m_eeprom_addr
unsigned char Power::m_eeprom_addr protected
This is the eeprom address calc from the m_id and the EEPROM_OFFSET
Definition at line 232 of file Power.h.
Referenced by load_param(), Power(), and update_param().
m_i_pin
unsigned char Power::m_i_pin protected
Definition at line 178 of file Power.h.
Referenced by load_param(), and update_param().
m_id
unsigned char Power::m_id protected
this the sensor's id in the Eeprom::sensor_counter
Definition at line 230 of file Power.h.
Referenced by Power(), and print().
m_v_pin
unsigned char Power::m_v_pin protected
Definition at line 177 of file Power.h.
Referenced by load_param(), read_rms_value(), and update_param().
p_average
double Power::p_average protected
there is the result from the real power average
Definition at line 187 of file Power.h.
Referenced by calc_all(), and print_average().
p_data
double Power::p_data[MAX_DATA_SAMPLE] ={0.0} protected
this is the data array where where real power data is stored and used to calculate the average.
Definition at line 183 of file Power.h.
Referenced by calc_all(), print_data_array(), and read_rms_value().
pf_average
double Power::pf_average protected
there is the result from the power factor average
Definition at line 189 of file Power.h.
Referenced by calc_all(), and print_average().
pf_data
double Power::pf_data[MAX_DATA_SAMPLE] ={0.0} protected
this is the data array where where power factor data is stored and used to calculate the average.
Definition at line 185 of file Power.h.
Referenced by calc_all(), print_data_array(), and read_rms_value().
referenceV
double Power::referenceV protected
Definition at line 217 of file Power.h.
Referenced by read_rms_value().
s_average
double Power::s_average protected
there is the result from the apparent power average
Definition at line 188 of file Power.h.
Referenced by calc_all(), and print_average().
s_data
double Power::s_data[MAX_DATA_SAMPLE] ={0.0} protected
this is the data array where where apparent power data is stored and used to calculate the average.
Definition at line 184 of file Power.h.
Referenced by calc_all(), print_data_array(), and read_rms_value().
showSupply
long Power::showSupply protected
Definition at line 219 of file Power.h.
Referenced by print_config(), and read_rms_value().
startV
int Power::startV protected
Definition at line 226 of file Power.h.
Referenced by read_rms_value().
sumI
long double Power::sumI protected
Definition at line 216 of file Power.h.
Referenced by read_rms_value().
sumP
long double Power::sumP protected
Variable that holds the voltage value after phase compensation
Definition at line 216 of file Power.h.
Referenced by read_rms_value().
sumV
long double Power::sumV protected
Definition at line 216 of file Power.h.
Referenced by read_rms_value().
v_average
double Power::v_average protected
there is the result from the m_data average
Definition at line 195 of file Power.h.
Referenced by calc_all(), and print_average().
v_data
double Power::v_data[MAX_DATA_SAMPLE] ={0.0} protected
this is the data array where voltage data is stored and used to calculate the average.
Definition at line 194 of file Power.h.
Referenced by calc_all(), print_data_array(), and read_rms_value().
v_factor
double Power::v_factor protected
Definition at line 196 of file Power.h.
Referenced by load_param(), print_config(), read_rms_value(), set_v_factor(), and update_param().
v_filtered
double Power::v_filtered protected
Definition at line 218 of file Power.h.
Referenced by read_rms_value().
v_offset
double Power::v_offset protected
this is the voltage calibration factor. it initial value is 1, but if the sensor data need to be multiply, change the factor value.
Definition at line 197 of file Power.h.
Referenced by load_param(), Power(), print_config(), read_rms_value(), set_v_offset(), and update_param().
v_phase
double Power::v_phase protected
this is the voltage offset. It initial value is zero. Change it if you want add an offset to the sensor's data.
Definition at line 198 of file Power.h.
Referenced by load_param(), print_config(), read_rms_value(), set_v_phase(), and update_param().
Vmeas
double Power::Vmeas protected
this is the current offset. It initial value is zero. Change it if you want add an offset to the sensor's data.
Definition at line 213 of file Power.h.
Referenced by Power(), and read_rms_value().
Vshifted
double Power::Vshifted protected
Variable that holds current measurement
Definition at line 215 of file Power.h.
Referenced by read_rms_value().
The documentation for this class was generated from the following files:
Power.h
Power.cpp