Windlogger: Config Class Reference
Config Class Reference
The class Config inherits from the class State. This class manage input between the FSM, the uarts (serial interface) and eeprom. With this class, the windlogger can display eeprom saved data and update there from the uart0. It can control time update with the DateTime class to have correct convertion from a human date and time display and the unix time stamp use by the logger to timestamp data.
#include <st_Config.h>
Public Member Functions
Config ()
Constructor.
virtual ~Config ()
Destructor.
virtual void execute ()
The execute method is the config "main function" In this method, sentence from the uart are process either to display the configuration menu or to update configuration register, if it's need, the eeprom are updated.
virtual void print ()
bool isEqual (char *name) const
void backspace ()
void endString ()
void display ()
display all config on USART0
void addToRequest (char c)
add c to the end of request
unsigned char atoc (char string[])
void load_logger ()
Load saved config data from the eeprom.
void update_logger ()
Update saved config data in the eeprom.
void initialize_logger ()
Initialize the eeprom memory.
Public Member Functions inherited from State
State ()
virtual ~State ()
bool isEqual (char *name) const
Private Attributes
DateTime currentTime
char request [20]
unsigned char request_i
Additional Inherited Members
Protected Attributes inherited from State
char m_name [10]
Detailed Description
Definition at line 50 of file st_Config.h.
Constructor & Destructor Documentation
Config()
Config::Config ()
Definition at line 50 of file st_Config.cpp.
References State::m_name.
~Config()
Config::~Config () virtual
Definition at line 55 of file st_Config.cpp.
Member Function Documentation
addToRequest()
void Config::addToRequest (char c)
Parameters
c is a char character
Definition at line 210 of file st_Config.cpp.
References request, and request_i.
Referenced by FSM::character_processing(), and endString().
atoc()
unsigned char Config::atoc (char string[])
This method convert a 2 character array in a char value
Parameters
string pointer to the dozen character
Returns
return the char value
Definition at line 216 of file st_Config.cpp.
Referenced by endString(), and execute().
backspace()
void Config::backspace () inline
This method decrements the request_i index when the backspace key is hit.
Definition at line 90 of file st_Config.h.
Referenced by FSM::character_processing().
display()
void Config::display ()
Returns
void
Definition at line 190 of file st_Config.cpp.
References FSM::logger, FSM::powerAC, Usart::print(), Sensor::print_config(), RTC::print_config(), Power::print_config(), FSM::rtc, FSM::timestamp, FSM::uart0, and FSM::windvane.
Referenced by endString(), and execute().
endString()
void Config::endString () inline
Put end string character '\0' to request
Definition at line 95 of file st_Config.h.
References addToRequest(), atoc(), display(), initialize_logger(), load_logger(), and update_logger().
Referenced by FSM::character_processing().
execute()
void Config::execute () virtual
Todo:
correct display bug
Implements State.
Definition at line 61 of file st_Config.cpp.
References FSM::anemo1, FSM::anemo2, atoc(), display(), FSM::logger, Logger::measure_counter, Logger::measure_max, Logger::measure_periode, Logger::measure_sample_conf, Logger::node_id, FSM::powerAC, Usart::print(), request, request_i, FSM::rtc, Sensor::set_factor(), Power::set_i_factor(), Power::set_i_offset(), Sensor::set_offset(), Power::set_v_factor(), Power::set_v_offset(), Power::set_v_phase(), FSM::timestamp, FSM::uart0, update_logger(), RTC::update_reg(), and FSM::windvane.
initialize_logger()
void Config::initialize_logger ()
Returns
void
Definition at line 243 of file st_Config.cpp.
References DATA_STRUCTURE_VERSION, load_logger(), FSM::logger, Logger::structure_version, and update_logger().
Referenced by endString(), and load_logger().
isEqual()
bool Config::isEqual (char * name) const
Definition at line 182 of file st_Config.cpp.
References State::isEqual().
load_logger()
void Config::load_logger ()
Returns
void
Definition at line 231 of file st_Config.cpp.
References DATA_STRUCTURE_VERSION, initialize_logger(), and FSM::logger.
Referenced by endString(), FSM::FSM(), and initialize_logger().
print()
void Config::print () virtual
It's just a simple method to display the state name, use to debug
Implements State.
Definition at line 177 of file st_Config.cpp.
References State::m_name, Usart::print(), and FSM::uart0.
update_logger()
void Config::update_logger ()
Returns
void
Definition at line 238 of file st_Config.cpp.
References FSM::logger.
Referenced by endString(), execute(), and initialize_logger().
Member Data Documentation
currentTime
DateTime Config::currentTime private
current time is the human readable side of the timestamp. Use for configuration.
Definition at line 52 of file st_Config.h.
request
char Config::request[20] private
is the char array use to save character from USART0
Definition at line 53 of file st_Config.h.
Referenced by addToRequest(), and execute().
request_i
unsigned char Config::request_i private
this is the request string's index
Definition at line 54 of file st_Config.h.
Referenced by addToRequest(), and execute().
The documentation for this class was generated from the following files:
st_Config.h
st_Config.cpp